# Generated by Django 4.1 on 2024-09-17 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 9, 17, 6, 47, 8, 303422, tzinfo=datetime.timezone.utc), null=True)),
            ],
        ),
    ]
